# Generated by Django 5.2.7 on 2025-10-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='stopwords',
        ),
        migrations.AddField(
            model_name='word',
            name='taboo_word_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='word',
            name='taboo_word_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='word',
            name='taboo_word_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='word',
            name='taboo_word_4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='word',
            name='taboo_word_5',
            field=models.CharField(default='', max_length=255),
        ),
    ]
